### ISSUE TITLE
asahi-nvram thread 'main' panicked at asahi-nvram/src/main.rs:65:10: 

### ISSUE THREAD

**Issue by galizin** [WhatAmISupposedToPutHere/asahi-nvram#31]
Hello,

I really enjoyed asahi-bless before it broke a couple of days ago. I figured that asahi-bless is changing nvram variables, so I tried asahi-nvram and got this:

asahi-nvram  
thread 'main' panicked at asahi-nvram/src/main.rs:65:10:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
  0:     0xaaab8bedee78 - <unknown>
  1:     0xaaab8beae3e8 - <unknown>
  2:     0xaaab8bebdb0c - <unknown>
  3:     0xaaab8bee2568 - <unknown>
  4:     0xaaab8bee2d50 - <unknown>
  5:     0xaaab8bee27e4 - <unknown>
  6:     0xaaab8bee2760 - <unknown>
  7:     0xaaab8bee2754 - <unknown>
  8:     0xaaab8be69e28 - <unknown>
  9:     0xaaab8be6a104 - <unknown>
 10:     0xaaab8be743d4 - <unknown>
 11:     0xaaab8be6bd2c - <unknown>
 12:     0xaaab8be730c0 - <unknown>
 13:     0xffff2c068434 - <unknown>
 14:     0xffff2c068508 - __libc_start_main
 15:     0xaaab8be6bc30 - <unknown>
 16:                0x0 - <unknown>
Aborted

I am running this on Apple M1 2020 macbook air. Some system info:

qlist -IRv | grep nvram

sys-apps/asahi-nvram-0.2.3::gentoo

uname -r

6.11.6-p2-asahi-dist

lsb_release -a

LSB Version:    n/a
Distributor ID: Gentoo
Description:    Gentoo Linux
Release:        2.17
Codename:       n/a

**Comment by WhatAmISupposedToPutHere** [comment]
What is the result of running `ls /dev/mtd/by-name/` on your machine?

**Comment by galizin** [comment]
I don't have it. I only have /dev/mtd0 and /dev/mtd0ro which are both files. Am i missing a driver?

**Comment by WhatAmISupposedToPutHere** [comment]
Can you make extra sure that you are running the latest version of m1n1, latest kernel, and so on. Also make sure you run the update-m1n1 script

**Comment by galizin** [comment]
As for update-m1n1, seems like I run it more often than necessary. m1n1 and kernel are provided by the overlay maintainers and are usually a bit out of date. As changing kernel involves updating m1n1, I prefer not to switch kernels out of fear to render machine unbootable. That is also why I do not have the latest and greatest. So I guess I'll just wait for an update. Thanks!

**Comment by jannau** [comment]
What's the result of `udevadm info -a /dev/mtd0`? The "/dev/mtd/by-name/*" symlinks are  created by `/usr/lib/udev/rules.d/60-persistent-storage-mtd.rules`

**Comment by galizin** [comment]
I don't have 60-persistent-storage-mtd.rules in /usr/lib/udev/rules.d

udevadm:
```
Udevadm info starts with the device specified by the devpath and then
walks up the chain of parent devices. It prints for every device
found, all possible attributes in the udev rules key format.
A rule to match, can be composed by the attributes of the device
and the attributes from one single parent device.

 looking at device '/devices/platform/soc/235104000.spi/spi_master/spi0/spi0.0/mtd/mtd0':
   KERNEL=="mtd0"
   SUBSYSTEM=="mtd"
   DRIVER==""
   ATTR{bad_blocks}=="0"
   ATTR{bbt_blocks}=="0"
   ATTR{bitflip_threshold}=="0"
   ATTR{corrected_bits}=="0"
   ATTR{ecc_failures}=="0"
   ATTR{ecc_step_size}=="0"
   ATTR{ecc_strength}=="0"
   ATTR{erasesize}=="65536"
   ATTR{flags}=="0xc00"
   ATTR{name}=="nvram"
   ATTR{numeraseregions}=="0"
   ATTR{offset}=="7340032"
   ATTR{oobavail}=="0"
   ATTR{oobsize}=="0"
   ATTR{power/control}=="auto"
   ATTR{power/runtime_active_time}=="0"
   ATTR{power/runtime_status}=="unsupported"
   ATTR{power/runtime_suspended_time}=="0"
   ATTR{size}=="1048576"
   ATTR{subpagesize}=="1"
   ATTR{type}=="nor"
   ATTR{writesize}=="1"

 looking at parent device '/devices/platform/soc/235104000.spi/spi_master/spi0/spi0.0':
   KERNELS=="spi0.0"
   SUBSYSTEMS=="spi"
   DRIVERS=="spi-nor"
   ATTRS{driver_override}==""
   ATTRS{power/control}=="auto"
   ATTRS{power/runtime_active_time}=="0"
   ATTRS{power/runtime_status}=="unsupported"
   ATTRS{power/runtime_suspended_time}=="0"
   ATTRS{spi-nor/jedec_id}=="c22537"
   ATTRS{spi-nor/manufacturer}=="macronix"
   ATTRS{spi-nor/partname}=="mx25u6435f"
   ATTRS{statistics/bytes}=="7"
   ATTRS{statistics/bytes_rx}=="6"
   ATTRS{statistics/bytes_tx}=="1"
   ATTRS{statistics/errors}=="0"
   ATTRS{statistics/messages}=="1"
   ATTRS{statistics/spi_async}=="0"
   ATTRS{statistics/spi_sync}=="1"
   ATTRS{statistics/spi_sync_immediate}=="1"
   ATTRS{statistics/timedout}=="0"
   ATTRS{statistics/transfer_bytes_histo_0-1}=="1"
   ATTRS{statistics/transfer_bytes_histo_1024-2047}=="0"
   ATTRS{statistics/transfer_bytes_histo_128-255}=="0"
   ATTRS{statistics/transfer_bytes_histo_16-31}=="0"
   ATTRS{statistics/transfer_bytes_histo_16384-32767}=="0"
   ATTRS{statistics/transfer_bytes_histo_2-3}=="0"
   ATTRS{statistics/transfer_bytes_histo_2048-4095}=="0"
   ATTRS{statistics/transfer_bytes_histo_256-511}=="0"
   ATTRS{statistics/transfer_bytes_histo_32-63}=="0"
   ATTRS{statistics/transfer_bytes_histo_32768-65535}=="0"
   ATTRS{statistics/transfer_bytes_histo_4-7}=="1"
   ATTRS{statistics/transfer_bytes_histo_4096-8191}=="0"
   ATTRS{statistics/transfer_bytes_histo_512-1023}=="0"
   ATTRS{statistics/transfer_bytes_histo_64-127}=="0"
   ATTRS{statistics/transfer_bytes_histo_65536+}=="0"
   ATTRS{statistics/transfer_bytes_histo_8-15}=="0"
   ATTRS{statistics/transfer_bytes_histo_8192-16383}=="0"
   ATTRS{statistics/transfers}=="2"
   ATTRS{statistics/transfers_split_maxsize}=="0"

 looking at parent device '/devices/platform/soc/235104000.spi/spi_master/spi0':
   KERNELS=="spi0"
   SUBSYSTEMS=="spi_master"
   DRIVERS==""
   ATTRS{power/control}=="auto"
   ATTRS{power/runtime_active_time}=="0"
   ATTRS{power/runtime_status}=="unsupported"
   ATTRS{power/runtime_suspended_time}=="0"
   ATTRS{statistics/bytes}=="7"
   ATTRS{statistics/bytes_rx}=="6"
   ATTRS{statistics/bytes_tx}=="1"
   ATTRS{statistics/errors}=="0"
   ATTRS{statistics/messages}=="1"
   ATTRS{statistics/spi_async}=="0"
   ATTRS{statistics/spi_sync}=="1"
   ATTRS{statistics/spi_sync_immediate}=="1"
   ATTRS{statistics/timedout}=="0"
   ATTRS{statistics/transfer_bytes_histo_0-1}=="1"
   ATTRS{statistics/transfer_bytes_histo_1024-2047}=="0"
   ATTRS{statistics/transfer_bytes_histo_128-255}=="0"
   ATTRS{statistics/transfer_bytes_histo_16-31}=="0"
   ATTRS{statistics/transfer_bytes_histo_16384-32767}=="0"
   ATTRS{statistics/transfer_bytes_histo_2-3}=="0"
   ATTRS{statistics/transfer_bytes_histo_2048-4095}=="0"
   ATTRS{statistics/transfer_bytes_histo_256-511}=="0"
   ATTRS{statistics/transfer_bytes_histo_32-63}=="0"
   ATTRS{statistics/transfer_bytes_histo_32768-65535}=="0"
   ATTRS{statistics/transfer_bytes_histo_4-7}=="1"
   ATTRS{statistics/transfer_bytes_histo_4096-8191}=="0"
   ATTRS{statistics/transfer_bytes_histo_512-1023}=="0"
   ATTRS{statistics/transfer_bytes_histo_64-127}=="0"
   ATTRS{statistics/transfer_bytes_histo_65536+}=="0"
   ATTRS{statistics/transfer_bytes_histo_8-15}=="0"
   ATTRS{statistics/transfer_bytes_histo_8192-16383}=="0"
   ATTRS{statistics/transfers}=="2"
   ATTRS{statistics/transfers_split_maxsize}=="0"

 looking at parent device '/devices/platform/soc/235104000.spi':
   KERNELS=="235104000.spi"
   SUBSYSTEMS=="platform"
   DRIVERS=="apple-spi"
   ATTRS{driver_override}=="(null)"
   ATTRS{power/control}=="auto"
   ATTRS{power/runtime_active_time}=="6"
   ATTRS{power/runtime_status}=="suspended"
   ATTRS{power/runtime_suspended_time}=="55886"

 looking at parent device '/devices/platform/soc':
   KERNELS=="soc"
   SUBSYSTEMS=="platform"
   DRIVERS=="simple-pm-bus"
   ATTRS{driver_override}=="(null)"
   ATTRS{power/control}=="auto"
   ATTRS{power/runtime_active_time}=="0"
   ATTRS{power/runtime_status}=="unsupported"
   ATTRS{power/runtime_suspended_time}=="0"

 looking at parent device '/devices/platform':
   KERNELS=="platform"
   SUBSYSTEMS==""
   DRIVERS==""
   ATTRS{power/control}=="auto"
   ATTRS{power/runtime_active_time}=="0"
   ATTRS{power/runtime_status}=="unsupported"
   ATTRS{power/runtime_suspended_time}=="0"

```

**Comment by WhatAmISupposedToPutHere** [comment]
```
equery b /usr/lib/udev/rules.d/60-persistent-storage-mtd.rules 
 * Searching for /usr/lib/udev/rules.d/60-persistent-storage-mtd.rules ... 
sys-apps/systemd-256.9 (/usr/lib/udev/rules.d/60-persistent-storage-mtd.rules)
```
I take it you run openrc?

**Comment by galizin** [comment]
correct

**Comment by WhatAmISupposedToPutHere** [comment]
You should ask the openrc maintainers to include the relevant udev rules (or switch to systemd :P). For now, here are the contents of the relevant file on my system, you can add it to your udev rules.
```
# do not edit this file, it will be overwritten on update

# persistent storage links: /dev/mtd/by-name

ACTION=="remove", GOTO="persistent_storage_mtd_end"
SUBSYSTEM!="mtd", GOTO="persistent_storage_mtd_end"
KERNEL!="mtd[0-9]*", GOTO="persistent_storage_mtd_end"
KERNEL=="mtd[0-9]*ro", GOTO="persistent_storage_mtd_end"

ATTR{name}=="?*", SYMLINK+="mtd/by-name/$attr{name}"

LABEL="persistent_storage_mtd_end"
```

**Comment by galizin** [comment]
that worked, thanks a lot!
